/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vdeccount24.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_clk[1024];
        extern "C" int port_clk;
        extern "C" int temp_reset[1024];
        extern "C" int port_reset;
        extern "C" int temp_q[1024];
        extern "C" int port_q;
        extern "C" int foodeccount24(int,int);
        
        void int2arrdeccount24(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intdeccount24(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foodeccount24(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vdeccount24* deccount24[1024];
            count--;
            if (init==0)
            {
                deccount24[count]=new Vdeccount24{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============deccount24 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("clk=%d\n", deccount24[count] ->clk);
				printf("reset=%d\n", deccount24[count] ->reset);
				printf("q=%d\n", deccount24[count] ->q);
				deccount24[count]->clk = arr2intdeccount24(temp_clk, port_clk);
				deccount24[count]->reset = arr2intdeccount24(temp_reset, port_reset);
				deccount24[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("clk=%d\n", deccount24[count] ->clk);
				printf("reset=%d\n", deccount24[count] ->reset);
				printf("q=%d\n", deccount24[count] ->q);
				int2arrdeccount24(deccount24[count] -> q, temp_q, port_q);

            }
            return 0;
        }