/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_freq4div11.h"

        
void cm_freq4div11(ARGS) 
{
	Digital_State_t *_op_COUNT, *_op_COUNT_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foofreq4div11(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_CLK=PORT_SIZE(CLK);

        port_COUNT=PORT_SIZE(COUNT);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(CLK);Ii++)
		{
			LOAD(CLK[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_COUNT = _op_COUNT_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_COUNT = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_COUNT_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(CLK);Ii++)
    {
        if( INPUT_STATE(CLK[Ii])==ZERO )
        {
            temp_CLK[Ii]=0;            }
        else
        {
            temp_CLK[Ii]=1;
        }
            }
	foofreq4div11(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(COUNT);Ii++)
    {
        if(temp_COUNT[Ii]==0)
        {
            _op_COUNT[Ii]=ZERO;
            }
        else if(temp_COUNT[Ii]==1)
        {
            _op_COUNT[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(COUNT[Ii]) = _op_COUNT[Ii];
            }
        else if(_op_COUNT[Ii] != _op_COUNT_old[Ii])
        {
            OUTPUT_STATE(COUNT[Ii]) = _op_COUNT[Ii];
            OUTPUT_DELAY(COUNT[Ii]) = ((_op_COUNT[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(COUNT[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(COUNT[Ii]) = STRONG;
    }

}