/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vfreq4div11.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_CLK[1024];
        extern "C" int port_CLK;
        extern "C" int temp_COUNT[1024];
        extern "C" int port_COUNT;
        extern "C" int foofreq4div11(int,int);
        
        void int2arrfreq4div11(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intfreq4div11(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foofreq4div11(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vfreq4div11* freq4div11[1024];
            count--;
            if (init==0)
            {
                freq4div11[count]=new Vfreq4div11{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============freq4div11 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("CLK=%d\n", freq4div11[count] ->CLK);
				printf("COUNT=%d\n", freq4div11[count] ->COUNT);
				freq4div11[count]->CLK = arr2intfreq4div11(temp_CLK, port_CLK);
				freq4div11[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("CLK=%d\n", freq4div11[count] ->CLK);
				printf("COUNT=%d\n", freq4div11[count] ->COUNT);
				int2arrfreq4div11(freq4div11[count] -> COUNT, temp_COUNT, port_COUNT);

            }
            return 0;
        }