/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_freq8div11.h"

        
void cm_freq8div11(ARGS) 
{
	Digital_State_t *_op_out_clk, *_op_out_clk_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foofreq8div11(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_clk=PORT_SIZE(clk);

        port_out_clk=PORT_SIZE(out_clk);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
		{
			LOAD(clk[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_out_clk = _op_out_clk_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_out_clk = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_out_clk_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
    {
        if( INPUT_STATE(clk[Ii])==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
	foofreq8div11(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(out_clk);Ii++)
    {
        if(temp_out_clk[Ii]==0)
        {
            _op_out_clk[Ii]=ZERO;
            }
        else if(temp_out_clk[Ii]==1)
        {
            _op_out_clk[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(out_clk[Ii]) = _op_out_clk[Ii];
            }
        else if(_op_out_clk[Ii] != _op_out_clk_old[Ii])
        {
            OUTPUT_STATE(out_clk[Ii]) = _op_out_clk[Ii];
            OUTPUT_DELAY(out_clk[Ii]) = ((_op_out_clk[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(out_clk[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(out_clk[Ii]) = STRONG;
    }

}