/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vfreq8div11.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_clk[1024];
        extern "C" int port_clk;
        extern "C" int temp_out_clk[1024];
        extern "C" int port_out_clk;
        extern "C" int foofreq8div11(int,int);
        
        void int2arrfreq8div11(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intfreq8div11(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foofreq8div11(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vfreq8div11* freq8div11[1024];
            count--;
            if (init==0)
            {
                freq8div11[count]=new Vfreq8div11{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============freq8div11 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("clk=%d\n", freq8div11[count] ->clk);
				printf("out_clk=%d\n", freq8div11[count] ->out_clk);
				freq8div11[count]->clk = arr2intfreq8div11(temp_clk, port_clk);
				freq8div11[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("clk=%d\n", freq8div11[count] ->clk);
				printf("out_clk=%d\n", freq8div11[count] ->out_clk);
				int2arrfreq8div11(freq8div11[count] -> out_clk, temp_out_clk, port_out_clk);

            }
            return 0;
        }