/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vbuf12.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_a[1024];
        extern "C" int port_a;
        extern "C" int temp_y[1024];
        extern "C" int port_y;
        extern "C" int temp_ybar[1024];
        extern "C" int port_ybar;
        extern "C" int foobuf12(int,int);
        
        void int2arrbuf12(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intbuf12(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foobuf12(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vbuf12* buf12[1024];
            count--;
            if (init==0)
            {
                buf12[count]=new Vbuf12{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============buf12 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("a=%d\n", buf12[count] ->a);
				printf("y=%d\n", buf12[count] ->y);
				printf("ybar=%d\n", buf12[count] ->ybar);
				buf12[count]->a = arr2intbuf12(temp_a, port_a);
				buf12[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("a=%d\n", buf12[count] ->a);
				printf("y=%d\n", buf12[count] ->y);
				printf("ybar=%d\n", buf12[count] ->ybar);
				int2arrbuf12(buf12[count] -> y, temp_y, port_y);
				int2arrbuf12(buf12[count] -> ybar, temp_ybar, port_ybar);

            }
            return 0;
        }