/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_srlatch32.h"

        
void cm_srlatch32(ARGS) 
{
	Digital_State_t *_op_Q, *_op_Q_old;
	Digital_State_t *_op_Qn, *_op_Qn_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foosrlatch32(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_CLK=PORT_SIZE(CLK);

        port_S=PORT_SIZE(S);

        port_R=PORT_SIZE(R);

        port_Q=PORT_SIZE(Q);

        port_Qn=PORT_SIZE(Qn);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		cm_event_alloc(1,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(CLK);Ii++)
		{
			LOAD(CLK[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(S);Ii++)
		{
			LOAD(S[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(R);Ii++)
		{
			LOAD(R[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_Q = _op_Q_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_Qn = _op_Qn_old = (Digital_State_t *) cm_event_get_ptr(1,0);


	}
	else
	{
		_op_Q = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_Q_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_Qn = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_Qn_old = (Digital_State_t *) cm_event_get_ptr(1,2);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(CLK);Ii++)
    {
        if( INPUT_STATE(CLK[Ii])==ZERO )
        {
            temp_CLK[Ii]=0;            }
        else
        {
            temp_CLK[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(S);Ii++)
    {
        if( INPUT_STATE(S[Ii])==ZERO )
        {
            temp_S[Ii]=0;            }
        else
        {
            temp_S[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(R);Ii++)
    {
        if( INPUT_STATE(R[Ii])==ZERO )
        {
            temp_R[Ii]=0;            }
        else
        {
            temp_R[Ii]=1;
        }
            }
	foosrlatch32(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(Q);Ii++)
    {
        if(temp_Q[Ii]==0)
        {
            _op_Q[Ii]=ZERO;
            }
        else if(temp_Q[Ii]==1)
        {
            _op_Q[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(Q[Ii]) = _op_Q[Ii];
            }
        else if(_op_Q[Ii] != _op_Q_old[Ii])
        {
            OUTPUT_STATE(Q[Ii]) = _op_Q[Ii];
            OUTPUT_DELAY(Q[Ii]) = ((_op_Q[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(Q[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(Q[Ii]) = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(Qn);Ii++)
    {
        if(temp_Qn[Ii]==0)
        {
            _op_Qn[Ii]=ZERO;
            }
        else if(temp_Qn[Ii]==1)
        {
            _op_Qn[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(Qn[Ii]) = _op_Qn[Ii];
            }
        else if(_op_Qn[Ii] != _op_Qn_old[Ii])
        {
            OUTPUT_STATE(Qn[Ii]) = _op_Qn[Ii];
            OUTPUT_DELAY(Qn[Ii]) = ((_op_Qn[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(Qn[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(Qn[Ii]) = STRONG;
    }

}