/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_fsmlock31.h"

        
void cm_fsmlock31(ARGS) 
{
	Digital_State_t *_op_pattern_detect, *_op_pattern_detect_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foofsmlock31(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_clk=PORT_SIZE(clk);

        port_reset=PORT_SIZE(reset);

        port_din=PORT_SIZE(din);

        port_pattern_detect=PORT_SIZE(pattern_detect);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
		{
			LOAD(clk[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(reset);Ii++)
		{
			LOAD(reset[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(din);Ii++)
		{
			LOAD(din[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_pattern_detect = _op_pattern_detect_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_pattern_detect = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_pattern_detect_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
    {
        if( INPUT_STATE(clk[Ii])==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(reset);Ii++)
    {
        if( INPUT_STATE(reset[Ii])==ZERO )
        {
            temp_reset[Ii]=0;            }
        else
        {
            temp_reset[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(din);Ii++)
    {
        if( INPUT_STATE(din[Ii])==ZERO )
        {
            temp_din[Ii]=0;            }
        else
        {
            temp_din[Ii]=1;
        }
            }
	foofsmlock31(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(pattern_detect);Ii++)
    {
        if(temp_pattern_detect[Ii]==0)
        {
            _op_pattern_detect[Ii]=ZERO;
            }
        else if(temp_pattern_detect[Ii]==1)
        {
            _op_pattern_detect[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(pattern_detect[Ii]) = _op_pattern_detect[Ii];
            }
        else if(_op_pattern_detect[Ii] != _op_pattern_detect_old[Ii])
        {
            OUTPUT_STATE(pattern_detect[Ii]) = _op_pattern_detect[Ii];
            OUTPUT_DELAY(pattern_detect[Ii]) = ((_op_pattern_detect[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(pattern_detect[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(pattern_detect[Ii]) = STRONG;
    }

}