/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vfsmlock31.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_clk[1024];
        extern "C" int port_clk;
        extern "C" int temp_reset[1024];
        extern "C" int port_reset;
        extern "C" int temp_din[1024];
        extern "C" int port_din;
        extern "C" int temp_pattern_detect[1024];
        extern "C" int port_pattern_detect;
        extern "C" int foofsmlock31(int,int);
        
        void int2arrfsmlock31(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intfsmlock31(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foofsmlock31(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vfsmlock31* fsmlock31[1024];
            count--;
            if (init==0)
            {
                fsmlock31[count]=new Vfsmlock31{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============fsmlock31 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("clk=%d\n", fsmlock31[count] ->clk);
				printf("reset=%d\n", fsmlock31[count] ->reset);
				printf("din=%d\n", fsmlock31[count] ->din);
				printf("pattern_detect=%d\n", fsmlock31[count] ->pattern_detect);
				fsmlock31[count]->clk = arr2intfsmlock31(temp_clk, port_clk);
				fsmlock31[count]->reset = arr2intfsmlock31(temp_reset, port_reset);
				fsmlock31[count]->din = arr2intfsmlock31(temp_din, port_din);
				fsmlock31[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("clk=%d\n", fsmlock31[count] ->clk);
				printf("reset=%d\n", fsmlock31[count] ->reset);
				printf("din=%d\n", fsmlock31[count] ->din);
				printf("pattern_detect=%d\n", fsmlock31[count] ->pattern_detect);
				int2arrfsmlock31(fsmlock31[count] -> pattern_detect, temp_pattern_detect, port_pattern_detect);

            }
            return 0;
        }