/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_pwm11.h"

        
void cm_pwm11(ARGS) 
{
	Digital_State_t *_op_led, *_op_led_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foopwm11(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_clk=PORT_SIZE(clk);

        port_led=PORT_SIZE(led);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
		{
			LOAD(clk[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_led = _op_led_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_led = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_led_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
    {
        if( INPUT_STATE(clk[Ii])==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
	foopwm11(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(led);Ii++)
    {
        if(temp_led[Ii]==0)
        {
            _op_led[Ii]=ZERO;
            }
        else if(temp_led[Ii]==1)
        {
            _op_led[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(led[Ii]) = _op_led[Ii];
            }
        else if(_op_led[Ii] != _op_led_old[Ii])
        {
            OUTPUT_STATE(led[Ii]) = _op_led[Ii];
            OUTPUT_DELAY(led[Ii]) = ((_op_led[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(led[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(led[Ii]) = STRONG;
    }

}