/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vpwm11.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_clk[1024];
        extern "C" int port_clk;
        extern "C" int temp_led[1024];
        extern "C" int port_led;
        extern "C" int foopwm11(int,int);
        
        void int2arrpwm11(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intpwm11(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foopwm11(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vpwm11* pwm11[1024];
            count--;
            if (init==0)
            {
                pwm11[count]=new Vpwm11{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============pwm11 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("clk=%d\n", pwm11[count] ->clk);
				printf("led=%d\n", pwm11[count] ->led);
				pwm11[count]->clk = arr2intpwm11(temp_clk, port_clk);
				pwm11[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("clk=%d\n", pwm11[count] ->clk);
				printf("led=%d\n", pwm11[count] ->led);
				int2arrpwm11(pwm11[count] -> led, temp_led, port_led);

            }
            return 0;
        }