/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_xor21.h"

        
void cm_xor21(ARGS) 
{
	Digital_State_t *_op_c, *_op_c_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        fooxor21(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_a=PORT_SIZE(a);

        port_b=PORT_SIZE(b);

        port_c=PORT_SIZE(c);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(a);Ii++)
		{
			LOAD(a[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(b);Ii++)
		{
			LOAD(b[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_c = _op_c_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_c = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_c_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(a);Ii++)
    {
        if( INPUT_STATE(a[Ii])==ZERO )
        {
            temp_a[Ii]=0;            }
        else
        {
            temp_a[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(b);Ii++)
    {
        if( INPUT_STATE(b[Ii])==ZERO )
        {
            temp_b[Ii]=0;            }
        else
        {
            temp_b[Ii]=1;
        }
            }
	fooxor21(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(c);Ii++)
    {
        if(temp_c[Ii]==0)
        {
            _op_c[Ii]=ZERO;
            }
        else if(temp_c[Ii]==1)
        {
            _op_c[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(c[Ii]) = _op_c[Ii];
            }
        else if(_op_c[Ii] != _op_c_old[Ii])
        {
            OUTPUT_STATE(c[Ii]) = _op_c[Ii];
            OUTPUT_DELAY(c[Ii]) = ((_op_c[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(c[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(c[Ii]) = STRONG;
    }

}