/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vxor21.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_a[1024];
        extern "C" int port_a;
        extern "C" int temp_b[1024];
        extern "C" int port_b;
        extern "C" int temp_c[1024];
        extern "C" int port_c;
        extern "C" int fooxor21(int,int);
        
        void int2arrxor21(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intxor21(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int fooxor21(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vxor21* xor21[1024];
            count--;
            if (init==0)
            {
                xor21[count]=new Vxor21{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============xor21 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("a=%d\n", xor21[count] ->a);
				printf("b=%d\n", xor21[count] ->b);
				printf("c=%d\n", xor21[count] ->c);
				xor21[count]->a = arr2intxor21(temp_a, port_a);
				xor21[count]->b = arr2intxor21(temp_b, port_b);
				xor21[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("a=%d\n", xor21[count] ->a);
				printf("b=%d\n", xor21[count] ->b);
				printf("c=%d\n", xor21[count] ->c);
				int2arrxor21(xor21[count] -> c, temp_c, port_c);

            }
            return 0;
        }