/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_mux21.h"

        
void cm_mux21(ARGS) 
{
	Digital_State_t *_op_y, *_op_y_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foomux21(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_i0=PORT_SIZE(i0);

        port_i1=PORT_SIZE(i1);

        port_sel=PORT_SIZE(sel);

        port_y=PORT_SIZE(y);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(i0);Ii++)
		{
			LOAD(i0[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(i1);Ii++)
		{
			LOAD(i1[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(sel);Ii++)
		{
			LOAD(sel[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_y = _op_y_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_y = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_y_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(i0);Ii++)
    {
        if( INPUT_STATE(i0[Ii])==ZERO )
        {
            temp_i0[Ii]=0;            }
        else
        {
            temp_i0[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(i1);Ii++)
    {
        if( INPUT_STATE(i1[Ii])==ZERO )
        {
            temp_i1[Ii]=0;            }
        else
        {
            temp_i1[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(sel);Ii++)
    {
        if( INPUT_STATE(sel[Ii])==ZERO )
        {
            temp_sel[Ii]=0;            }
        else
        {
            temp_sel[Ii]=1;
        }
            }
	foomux21(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(y);Ii++)
    {
        if(temp_y[Ii]==0)
        {
            _op_y[Ii]=ZERO;
            }
        else if(temp_y[Ii]==1)
        {
            _op_y[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(y[Ii]) = _op_y[Ii];
            }
        else if(_op_y[Ii] != _op_y_old[Ii])
        {
            OUTPUT_STATE(y[Ii]) = _op_y[Ii];
            OUTPUT_DELAY(y[Ii]) = ((_op_y[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(y[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(y[Ii]) = STRONG;
    }

}