/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_piso12_1.h"

        
void cm_piso12_1(ARGS) 
{
	Digital_State_t *_op_Data_sr, *_op_Data_sr_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foopiso12_1(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_clk=PORT_SIZE(clk);

        port_load=PORT_SIZE(load);

        port_Data_pr=PORT_SIZE(Data_pr);

        port_Data_sr=PORT_SIZE(Data_sr);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
		{
			LOAD(clk[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(load);Ii++)
		{
			LOAD(load[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(Data_pr);Ii++)
		{
			LOAD(Data_pr[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_Data_sr = _op_Data_sr_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_Data_sr = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_Data_sr_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
    {
        if( INPUT_STATE(clk[Ii])==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(load);Ii++)
    {
        if( INPUT_STATE(load[Ii])==ZERO )
        {
            temp_load[Ii]=0;            }
        else
        {
            temp_load[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(Data_pr);Ii++)
    {
        if( INPUT_STATE(Data_pr[Ii])==ZERO )
        {
            temp_Data_pr[Ii]=0;            }
        else
        {
            temp_Data_pr[Ii]=1;
        }
            }
	foopiso12_1(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(Data_sr);Ii++)
    {
        if(temp_Data_sr[Ii]==0)
        {
            _op_Data_sr[Ii]=ZERO;
            }
        else if(temp_Data_sr[Ii]==1)
        {
            _op_Data_sr[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(Data_sr[Ii]) = _op_Data_sr[Ii];
            }
        else if(_op_Data_sr[Ii] != _op_Data_sr_old[Ii])
        {
            OUTPUT_STATE(Data_sr[Ii]) = _op_Data_sr[Ii];
            OUTPUT_DELAY(Data_sr[Ii]) = ((_op_Data_sr[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(Data_sr[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(Data_sr[Ii]) = STRONG;
    }

}