/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_sram6t23.h"

        
void cm_sram6t23(ARGS) 
{
	Digital_State_t *_op_q, *_op_q_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foosram6t23(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_din=PORT_SIZE(din);

        port_wen=PORT_SIZE(wen);

        port_q=PORT_SIZE(q);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(din);Ii++)
		{
			LOAD(din[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(wen);Ii++)
		{
			LOAD(wen[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_q = _op_q_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_q = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_q_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(din);Ii++)
    {
        if( INPUT_STATE(din[Ii])==ZERO )
        {
            temp_din[Ii]=0;            }
        else
        {
            temp_din[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(wen);Ii++)
    {
        if( INPUT_STATE(wen[Ii])==ZERO )
        {
            temp_wen[Ii]=0;            }
        else
        {
            temp_wen[Ii]=1;
        }
            }
	foosram6t23(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(q);Ii++)
    {
        if(temp_q[Ii]==0)
        {
            _op_q[Ii]=ZERO;
            }
        else if(temp_q[Ii]==1)
        {
            _op_q[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(q[Ii]) = _op_q[Ii];
            }
        else if(_op_q[Ii] != _op_q_old[Ii])
        {
            OUTPUT_STATE(q[Ii]) = _op_q[Ii];
            OUTPUT_DELAY(q[Ii]) = ((_op_q[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(q[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(q[Ii]) = STRONG;
    }

}