/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vsram6t23.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_din[1024];
        extern "C" int port_din;
        extern "C" int temp_wen[1024];
        extern "C" int port_wen;
        extern "C" int temp_q[1024];
        extern "C" int port_q;
        extern "C" int foosram6t23(int,int);
        
        void int2arrsram6t23(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intsram6t23(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foosram6t23(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vsram6t23* sram6t23[1024];
            count--;
            if (init==0)
            {
                sram6t23[count]=new Vsram6t23{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============sram6t23 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("din=%d\n", sram6t23[count] ->din);
				printf("wen=%d\n", sram6t23[count] ->wen);
				printf("q=%d\n", sram6t23[count] ->q);
				sram6t23[count]->din = arr2intsram6t23(temp_din, port_din);
				sram6t23[count]->wen = arr2intsram6t23(temp_wen, port_wen);
				sram6t23[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("din=%d\n", sram6t23[count] ->din);
				printf("wen=%d\n", sram6t23[count] ->wen);
				printf("q=%d\n", sram6t23[count] ->q);
				int2arrsram6t23(sram6t23[count] -> q, temp_q, port_q);

            }
            return 0;
        }