/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vcount23.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_clk[1024];
        extern "C" int port_clk;
        extern "C" int temp_reset[1024];
        extern "C" int port_reset;
        extern "C" int temp_counter[1024];
        extern "C" int port_counter;
        extern "C" int foocount23(int,int);
        
        void int2arrcount23(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intcount23(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foocount23(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vcount23* count23[1024];
            count--;
            if (init==0)
            {
                count23[count]=new Vcount23{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============count23 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("clk=%d\n", count23[count] ->clk);
				printf("reset=%d\n", count23[count] ->reset);
				printf("counter=%d\n", count23[count] ->counter);
				count23[count]->clk = arr2intcount23(temp_clk, port_clk);
				count23[count]->reset = arr2intcount23(temp_reset, port_reset);
				count23[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("clk=%d\n", count23[count] ->clk);
				printf("reset=%d\n", count23[count] ->reset);
				printf("counter=%d\n", count23[count] ->counter);
				int2arrcount23(count23[count] -> counter, temp_counter, port_counter);

            }
            return 0;
        }