/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vinv11.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_inv_in[1024];
        extern "C" int port_inv_in;
        extern "C" int temp_inv_out[1024];
        extern "C" int port_inv_out;
        extern "C" int fooinv11(int,int);
        
        void int2arrinv11(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intinv11(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int fooinv11(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vinv11* inv11[1024];
            count--;
            if (init==0)
            {
                inv11[count]=new Vinv11{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============inv11 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("inv_in=%d\n", inv11[count] ->inv_in);
				printf("inv_out=%d\n", inv11[count] ->inv_out);
				inv11[count]->inv_in = arr2intinv11(temp_inv_in, port_inv_in);
				inv11[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("inv_in=%d\n", inv11[count] ->inv_in);
				printf("inv_out=%d\n", inv11[count] ->inv_out);
				int2arrinv11(inv11[count] -> inv_out, temp_inv_out, port_inv_out);

            }
            return 0;
        }