/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_seqdetect31.h"

        
void cm_seqdetect31(ARGS) 
{
	Digital_State_t *_op_Z, *_op_Z_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        fooseqdetect31(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_I=PORT_SIZE(I);

        port_CLK=PORT_SIZE(CLK);

        port_RST=PORT_SIZE(RST);

        port_Z=PORT_SIZE(Z);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(I);Ii++)
		{
			LOAD(I[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(CLK);Ii++)
		{
			LOAD(CLK[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(RST);Ii++)
		{
			LOAD(RST[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_Z = _op_Z_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_Z = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_Z_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(I);Ii++)
    {
        if( INPUT_STATE(I[Ii])==ZERO )
        {
            temp_I[Ii]=0;            }
        else
        {
            temp_I[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(CLK);Ii++)
    {
        if( INPUT_STATE(CLK[Ii])==ZERO )
        {
            temp_CLK[Ii]=0;            }
        else
        {
            temp_CLK[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(RST);Ii++)
    {
        if( INPUT_STATE(RST[Ii])==ZERO )
        {
            temp_RST[Ii]=0;            }
        else
        {
            temp_RST[Ii]=1;
        }
            }
	fooseqdetect31(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(Z);Ii++)
    {
        if(temp_Z[Ii]==0)
        {
            _op_Z[Ii]=ZERO;
            }
        else if(temp_Z[Ii]==1)
        {
            _op_Z[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(Z[Ii]) = _op_Z[Ii];
            }
        else if(_op_Z[Ii] != _op_Z_old[Ii])
        {
            OUTPUT_STATE(Z[Ii]) = _op_Z[Ii];
            OUTPUT_DELAY(Z[Ii]) = ((_op_Z[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(Z[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(Z[Ii]) = STRONG;
    }

}