int fooseqdetect31(int,int);
        int temp_I[1024];
        int port_I;
        int temp_CLK[1024];
        int port_CLK;
        int temp_RST[1024];
        int port_RST;
        int temp_Z[1024];
        int port_Z;