/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vseqdetect31.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_I[1024];
        extern "C" int port_I;
        extern "C" int temp_CLK[1024];
        extern "C" int port_CLK;
        extern "C" int temp_RST[1024];
        extern "C" int port_RST;
        extern "C" int temp_Z[1024];
        extern "C" int port_Z;
        extern "C" int fooseqdetect31(int,int);
        
        void int2arrseqdetect31(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intseqdetect31(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int fooseqdetect31(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vseqdetect31* seqdetect31[1024];
            count--;
            if (init==0)
            {
                seqdetect31[count]=new Vseqdetect31{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============seqdetect31 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("I=%d\n", seqdetect31[count] ->I);
				printf("CLK=%d\n", seqdetect31[count] ->CLK);
				printf("RST=%d\n", seqdetect31[count] ->RST);
				printf("Z=%d\n", seqdetect31[count] ->Z);
				seqdetect31[count]->I = arr2intseqdetect31(temp_I, port_I);
				seqdetect31[count]->CLK = arr2intseqdetect31(temp_CLK, port_CLK);
				seqdetect31[count]->RST = arr2intseqdetect31(temp_RST, port_RST);
				seqdetect31[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("I=%d\n", seqdetect31[count] ->I);
				printf("CLK=%d\n", seqdetect31[count] ->CLK);
				printf("RST=%d\n", seqdetect31[count] ->RST);
				printf("Z=%d\n", seqdetect31[count] ->Z);
				int2arrseqdetect31(seqdetect31[count] -> Z, temp_Z, port_Z);

            }
            return 0;
        }