/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vdecode48.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_in[1024];
        extern "C" int port_in;
        extern "C" int temp_en[1024];
        extern "C" int port_en;
        extern "C" int temp_out[1024];
        extern "C" int port_out;
        extern "C" int foodecode48(int,int);
        
        void int2arrdecode48(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intdecode48(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foodecode48(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vdecode48* decode48[1024];
            count--;
            if (init==0)
            {
                decode48[count]=new Vdecode48{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============decode48 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("in=%d\n", decode48[count] ->in);
				printf("en=%d\n", decode48[count] ->en);
				printf("out=%d\n", decode48[count] ->out);
				decode48[count]->in = arr2intdecode48(temp_in, port_in);
				decode48[count]->en = arr2intdecode48(temp_en, port_en);
				decode48[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("in=%d\n", decode48[count] ->in);
				printf("en=%d\n", decode48[count] ->en);
				printf("out=%d\n", decode48[count] ->out);
				int2arrdecode48(decode48[count] -> out, temp_out, port_out);

            }
            return 0;
        }