/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vpriencode16_4.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_i[1024];
        extern "C" int port_i;
        extern "C" int temp_out[1024];
        extern "C" int port_out;
        extern "C" int foopriencode16_4(int,int);
        
        void int2arrpriencode16_4(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intpriencode16_4(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foopriencode16_4(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vpriencode16_4* priencode16_4[1024];
            count--;
            if (init==0)
            {
                priencode16_4[count]=new Vpriencode16_4{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============priencode16_4 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("i=%d\n", priencode16_4[count] ->i);
				printf("out=%d\n", priencode16_4[count] ->out);
				priencode16_4[count]->i = arr2intpriencode16_4(temp_i, port_i);
				priencode16_4[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("i=%d\n", priencode16_4[count] ->i);
				printf("out=%d\n", priencode16_4[count] ->out);
				int2arrpriencode16_4(priencode16_4[count] -> out, temp_out, port_out);

            }
            return 0;
        }