/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vjscount24.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_clk[1024];
        extern "C" int port_clk;
        extern "C" int temp_reset[1024];
        extern "C" int port_reset;
        extern "C" int temp_out[1024];
        extern "C" int port_out;
        extern "C" int foojscount24(int,int);
        
        void int2arrjscount24(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intjscount24(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foojscount24(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vjscount24* jscount24[1024];
            count--;
            if (init==0)
            {
                jscount24[count]=new Vjscount24{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============jscount24 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("clk=%d\n", jscount24[count] ->clk);
				printf("reset=%d\n", jscount24[count] ->reset);
				printf("out=%d\n", jscount24[count] ->out);
				jscount24[count]->clk = arr2intjscount24(temp_clk, port_clk);
				jscount24[count]->reset = arr2intjscount24(temp_reset, port_reset);
				jscount24[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("clk=%d\n", jscount24[count] ->clk);
				printf("reset=%d\n", jscount24[count] ->reset);
				printf("out=%d\n", jscount24[count] ->out);
				int2arrjscount24(jscount24[count] -> out, temp_out, port_out);

            }
            return 0;
        }