/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_mux61.h"

        
void cm_mux61(ARGS) 
{
	Digital_State_t *_op_out, *_op_out_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foomux61(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_a=PORT_SIZE(a);

        port_b=PORT_SIZE(b);

        port_c=PORT_SIZE(c);

        port_d=PORT_SIZE(d);

        port_s0=PORT_SIZE(s0);

        port_s1=PORT_SIZE(s1);

        port_out=PORT_SIZE(out);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(a);Ii++)
		{
			LOAD(a[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(b);Ii++)
		{
			LOAD(b[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(c);Ii++)
		{
			LOAD(c[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(d);Ii++)
		{
			LOAD(d[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(s0);Ii++)
		{
			LOAD(s0[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(s1);Ii++)
		{
			LOAD(s1[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_out = _op_out_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_out = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_out_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(a);Ii++)
    {
        if( INPUT_STATE(a[Ii])==ZERO )
        {
            temp_a[Ii]=0;            }
        else
        {
            temp_a[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(b);Ii++)
    {
        if( INPUT_STATE(b[Ii])==ZERO )
        {
            temp_b[Ii]=0;            }
        else
        {
            temp_b[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(c);Ii++)
    {
        if( INPUT_STATE(c[Ii])==ZERO )
        {
            temp_c[Ii]=0;            }
        else
        {
            temp_c[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(d);Ii++)
    {
        if( INPUT_STATE(d[Ii])==ZERO )
        {
            temp_d[Ii]=0;            }
        else
        {
            temp_d[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(s0);Ii++)
    {
        if( INPUT_STATE(s0[Ii])==ZERO )
        {
            temp_s0[Ii]=0;            }
        else
        {
            temp_s0[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(s1);Ii++)
    {
        if( INPUT_STATE(s1[Ii])==ZERO )
        {
            temp_s1[Ii]=0;            }
        else
        {
            temp_s1[Ii]=1;
        }
            }
	foomux61(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(out);Ii++)
    {
        if(temp_out[Ii]==0)
        {
            _op_out[Ii]=ZERO;
            }
        else if(temp_out[Ii]==1)
        {
            _op_out[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(out[Ii]) = _op_out[Ii];
            }
        else if(_op_out[Ii] != _op_out_old[Ii])
        {
            OUTPUT_STATE(out[Ii]) = _op_out[Ii];
            OUTPUT_DELAY(out[Ii]) = ((_op_out[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(out[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(out[Ii]) = STRONG;
    }

}