/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_priencode83.h"

        
void cm_priencode83(ARGS) 
{
	Digital_State_t *_op_dout, *_op_dout_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foopriencode83(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_din=PORT_SIZE(din);

        port_dout=PORT_SIZE(dout);
		cm_event_alloc(0,3*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(din);Ii++)
		{
			LOAD(din[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_dout = _op_dout_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_dout = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_dout_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(din);Ii++)
    {
        if( INPUT_STATE(din[Ii])==ZERO )
        {
            temp_din[Ii]=0;            }
        else
        {
            temp_din[Ii]=1;
        }
            }
	foopriencode83(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(dout);Ii++)
    {
        if(temp_dout[Ii]==0)
        {
            _op_dout[Ii]=ZERO;
            }
        else if(temp_dout[Ii]==1)
        {
            _op_dout[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(dout[Ii]) = _op_dout[Ii];
            }
        else if(_op_dout[Ii] != _op_dout_old[Ii])
        {
            OUTPUT_STATE(dout[Ii]) = _op_dout[Ii];
            OUTPUT_DELAY(dout[Ii]) = ((_op_dout[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(dout[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(dout[Ii]) = STRONG;
    }

}