/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vpriencode83.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_din[1024];
        extern "C" int port_din;
        extern "C" int temp_dout[1024];
        extern "C" int port_dout;
        extern "C" int foopriencode83(int,int);
        
        void int2arrpriencode83(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intpriencode83(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foopriencode83(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vpriencode83* priencode83[1024];
            count--;
            if (init==0)
            {
                priencode83[count]=new Vpriencode83{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============priencode83 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("din=%d\n", priencode83[count] ->din);
				printf("dout=%d\n", priencode83[count] ->dout);
				priencode83[count]->din = arr2intpriencode83(temp_din, port_din);
				priencode83[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("din=%d\n", priencode83[count] ->din);
				printf("dout=%d\n", priencode83[count] ->dout);
				int2arrpriencode83(priencode83[count] -> dout, temp_dout, port_dout);

            }
            return 0;
        }