/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vfulladd32.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_a[1024];
        extern "C" int port_a;
        extern "C" int temp_b[1024];
        extern "C" int port_b;
        extern "C" int temp_c_in[1024];
        extern "C" int port_c_in;
        extern "C" int temp_s[1024];
        extern "C" int port_s;
        extern "C" int temp_c_out[1024];
        extern "C" int port_c_out;
        extern "C" int foofulladd32(int,int);
        
        void int2arrfulladd32(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intfulladd32(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foofulladd32(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vfulladd32* fulladd32[1024];
            count--;
            if (init==0)
            {
                fulladd32[count]=new Vfulladd32{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============fulladd32 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("a=%d\n", fulladd32[count] ->a);
				printf("b=%d\n", fulladd32[count] ->b);
				printf("c_in=%d\n", fulladd32[count] ->c_in);
				printf("s=%d\n", fulladd32[count] ->s);
				printf("c_out=%d\n", fulladd32[count] ->c_out);
				fulladd32[count]->a = arr2intfulladd32(temp_a, port_a);
				fulladd32[count]->b = arr2intfulladd32(temp_b, port_b);
				fulladd32[count]->c_in = arr2intfulladd32(temp_c_in, port_c_in);
				fulladd32[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("a=%d\n", fulladd32[count] ->a);
				printf("b=%d\n", fulladd32[count] ->b);
				printf("c_in=%d\n", fulladd32[count] ->c_in);
				printf("s=%d\n", fulladd32[count] ->s);
				printf("c_out=%d\n", fulladd32[count] ->c_out);
				int2arrfulladd32(fulladd32[count] -> s, temp_s, port_s);
				int2arrfulladd32(fulladd32[count] -> c_out, temp_c_out, port_c_out);

            }
            return 0;
        }