/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vdaddamul88.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_A[1024];
        extern "C" int port_A;
        extern "C" int temp_B[1024];
        extern "C" int port_B;
        extern "C" int temp_Y[1024];
        extern "C" int port_Y;
        extern "C" int foodaddamul88(int,int);
        
        void int2arrdaddamul88(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intdaddamul88(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foodaddamul88(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vdaddamul88* daddamul88[1024];
            count--;
            if (init==0)
            {
                daddamul88[count]=new Vdaddamul88{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============daddamul88 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("A=%d\n", daddamul88[count] ->A);
				printf("B=%d\n", daddamul88[count] ->B);
				printf("Y=%d\n", daddamul88[count] ->Y);
				daddamul88[count]->A = arr2intdaddamul88(temp_A, port_A);
				daddamul88[count]->B = arr2intdaddamul88(temp_B, port_B);
				daddamul88[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("A=%d\n", daddamul88[count] ->A);
				printf("B=%d\n", daddamul88[count] ->B);
				printf("Y=%d\n", daddamul88[count] ->Y);
				int2arrdaddamul88(daddamul88[count] -> Y, temp_Y, port_Y);

            }
            return 0;
        }