/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_fullsub32.h"

        
void cm_fullsub32(ARGS) 
{
	Digital_State_t *_op_D, *_op_D_old;
	Digital_State_t *_op_B, *_op_B_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foofullsub32(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_X=PORT_SIZE(X);

        port_Y=PORT_SIZE(Y);

        port_Z=PORT_SIZE(Z);

        port_D=PORT_SIZE(D);

        port_B=PORT_SIZE(B);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		cm_event_alloc(1,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(X);Ii++)
		{
			LOAD(X[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(Y);Ii++)
		{
			LOAD(Y[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(Z);Ii++)
		{
			LOAD(Z[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_D = _op_D_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_B = _op_B_old = (Digital_State_t *) cm_event_get_ptr(1,0);


	}
	else
	{
		_op_D = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_D_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_B = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_B_old = (Digital_State_t *) cm_event_get_ptr(1,2);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(X);Ii++)
    {
        if( INPUT_STATE(X[Ii])==ZERO )
        {
            temp_X[Ii]=0;            }
        else
        {
            temp_X[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(Y);Ii++)
    {
        if( INPUT_STATE(Y[Ii])==ZERO )
        {
            temp_Y[Ii]=0;            }
        else
        {
            temp_Y[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(Z);Ii++)
    {
        if( INPUT_STATE(Z[Ii])==ZERO )
        {
            temp_Z[Ii]=0;            }
        else
        {
            temp_Z[Ii]=1;
        }
            }
	foofullsub32(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(D);Ii++)
    {
        if(temp_D[Ii]==0)
        {
            _op_D[Ii]=ZERO;
            }
        else if(temp_D[Ii]==1)
        {
            _op_D[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(D[Ii]) = _op_D[Ii];
            }
        else if(_op_D[Ii] != _op_D_old[Ii])
        {
            OUTPUT_STATE(D[Ii]) = _op_D[Ii];
            OUTPUT_DELAY(D[Ii]) = ((_op_D[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(D[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(D[Ii]) = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(B);Ii++)
    {
        if(temp_B[Ii]==0)
        {
            _op_B[Ii]=ZERO;
            }
        else if(temp_B[Ii]==1)
        {
            _op_B[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(B[Ii]) = _op_B[Ii];
            }
        else if(_op_B[Ii] != _op_B_old[Ii])
        {
            OUTPUT_STATE(B[Ii]) = _op_B[Ii];
            OUTPUT_DELAY(B[Ii]) = ((_op_B[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(B[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(B[Ii]) = STRONG;
    }

}