/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vcount24.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_clk[1024];
        extern "C" int port_clk;
        extern "C" int temp_rst[1024];
        extern "C" int port_rst;
        extern "C" int temp_count[1024];
        extern "C" int port_count;
        extern "C" int foocount24(int,int);
        
        void int2arrcount24(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intcount24(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foocount24(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vcount24* count24[1024];
            count--;
            if (init==0)
            {
                count24[count]=new Vcount24{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============count24 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("clk=%d\n", count24[count] ->clk);
				printf("rst=%d\n", count24[count] ->rst);
				printf("count=%d\n", count24[count] ->count);
				count24[count]->clk = arr2intcount24(temp_clk, port_clk);
				count24[count]->rst = arr2intcount24(temp_rst, port_rst);
				count24[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("clk=%d\n", count24[count] ->clk);
				printf("rst=%d\n", count24[count] ->rst);
				printf("count=%d\n", count24[count] ->count);
				int2arrcount24(count24[count] -> count, temp_count, port_count);

            }
            return 0;
        }