/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_staircase14.h"

        
void cm_staircase14(ARGS) 
{
	Digital_State_t *_op_val, *_op_val_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {
        inst_count++;
        PARAM(instance_id)=inst_count;
        foostaircase14(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_clk=PORT_SIZE(clk);

        port_val=PORT_SIZE(val);
		cm_event_alloc(0,4*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
		{
			LOAD(clk[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_val = _op_val_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_val = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_val_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
    {
        if( INPUT_STATE(clk[Ii])==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
	foostaircase14(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(val);Ii++)
    {
        if(temp_val[Ii]==0)
        {
            _op_val[Ii]=ZERO;
            }
        else if(temp_val[Ii]==1)
        {
            _op_val[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(val[Ii]) = _op_val[Ii];
            }
        else if(_op_val[Ii] != _op_val_old[Ii])
        {
            OUTPUT_STATE(val[Ii]) = _op_val[Ii];
            OUTPUT_DELAY(val[Ii]) = ((_op_val[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(val[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(val[Ii]) = STRONG;
    }

}