/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vmux20_4.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_in[1024];
        extern "C" int port_in;
        extern "C" int temp_s[1024];
        extern "C" int port_s;
        extern "C" int temp_out[1024];
        extern "C" int port_out;
        extern "C" int foomux20_4(int,int);
        
        void int2arrmux20_4(int  num, int array[], int n)
        {
            for (int i = 0; i < n && num>=0; i++)
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intmux20_4(int array[],int n)
        {
            int i,k=0;
            for (i = 0; i < n; i++)
                k = 2 * k + array[i];
            return k;
        }
        
        int foomux20_4(int init,int count)
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vmux20_4* mux20_4[1024];
            count--;
            if (init==0)
            {
                mux20_4[count]=new Vmux20_4{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============mux20_4 : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("in=%d\n", mux20_4[count] ->in);
				printf("s=%d\n", mux20_4[count] ->s);
				printf("out=%d\n", mux20_4[count] ->out);
				mux20_4[count]->in = arr2intmux20_4(temp_in, port_in);
				mux20_4[count]->s = arr2intmux20_4(temp_s, port_s);
				mux20_4[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("in=%d\n", mux20_4[count] ->in);
				printf("s=%d\n", mux20_4[count] ->s);
				printf("out=%d\n", mux20_4[count] ->out);
				int2arrmux20_4(mux20_4[count] -> out, temp_out, port_out);

            }
            return 0;
        }